name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          exclude_assets: '.github,.gitignore,*.py,*.log,jsd_test.txt,gh_*.txt,gh_*.txt,ct_test.txt,hdr1.txt,hdr2.txt,hdr1_u.txt,hdr2_u.txt'
          enable_jekyll: false
          keep_files: false
